blank_issues_enabled: false
contact_links:
  - name: Feature Request
    url: https://github.com/HPDCollaborative/builder-api/discussions/new?category=feature-requests
    about: Suggest a feature for the Builder API
