blank_issues_enabled: false
contact_links:
  - name: 💡 Feature Request
    url: https://github.com/HPDCollaborative/builder-api/discussions/categories/feature-requests
    about: Please suggest new features in our Feature Request Discussion board
